### ISSUE TITLE
https://viper.li/ is down

### ISSUE THREAD

**Issue by abitrolly** [viper-framework/viper-web#14]
https://viper.li/

**Comment by frennkie** [comment]
@botherder: viper.li does not seems to have an A record at the moment.

www.viper.li has a CNAME entry but this looks broken too: readthedocs.org.viper.li (I guess this should point to: viper-framework.readthedocs.io)

**Comment by botherder** [comment]
I can't really figure how to configure the canonical domain properly, so I fixed the records for now to just redirect to the RTD page.

**Comment by abitrolly** [comment]
There is also a problem with server SSL certificate. It would be easier to switch to let's encrypt for that.

**Comment by botherder** [comment]
This should all be handled by RTD. I do not know why it is not working properly. To be honest, I do not have enough time to set up any alternative system, and I think that for our purpose https://viper-framework.readthedocs.io/ will do just fine.
